### ISSUE TITLE
Invariance "MANAGER.__dict__ == manager.AstroidManager.brain" no longer holds

### ISSUE THREAD

**Issue by knedlsepp** [pylint-dev/astroid#2200]
### Steps to reproduce
Up until commit bbcc58bd52e7f295b77a8618b19b2364625590a2 the following equality would be guaranteed:

```
assert MANAGER.always_load_extensions == manager.AstroidManager.brain['always_load_extensions']
```

This apparently causes https://github.com/pylint-dev/pylint/issues/7433

**Comment by jacobtylerwalls** [comment]
Thanks! 

Looks like assigning to the attributes of AstroidManager (rather than mutating the existing values) is unsafe, as it will never "talk back" to the global state on the class.

We should get rid of the instance attributes. We could rewrite them as properties that mutate the global state when set, or we could also just prevent instantiation of AstroidManager at all, forcing everyone to deal with the global state. The former is the slimmer fix. Would you like to prepare a patch?
